"use client";

import {
  Home,
  Send,
  MessageCircle,
  CreditCard,
  FileText,
  Users,
  Upload,
  BarChart3,
  Plug,
  Settings,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Info,
  Target,
  RefreshCw,
  Lightbulb,
  Bell,
  ChevronDown,
  ArrowRight,
  ArrowUpRight,
  TrendingUp,
  Shield,
  Lock,
  Sparkles,
  Menu,
  Phone,
  Zap,
  Building2,
  Calendar,
  Plus,
  Search,
  Filter,
  MoreHorizontal,
  Pause,
  Play,
  FileSpreadsheet,
  Download,
  Loader2,
  Bot,
  User,
  AlertCircle,
  CheckCheck,
  Signal,
  Brain,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  home: Home,
  send: Send,
  chat: MessageCircle,
  card: CreditCard,
  file: FileText,
  users: Users,
  upload: Upload,
  chart: BarChart3,
  plug: Plug,
  gear: Settings,
  target: Target,
  refresh: RefreshCw,
  check: CheckCircle2,
  x: XCircle,
  warn: AlertTriangle,
  info: Info,
  bulb: Lightbulb,
  bell: Bell,
  chevron: ChevronDown,
  arrow: ArrowRight,
  arrowUpRight: ArrowUpRight,
  trend: TrendingUp,
  shield: Shield,
  lock: Lock,
  spark: Sparkles,
  menu: Menu,
  phone: Phone,
  zap: Zap,
  building: Building2,
  calendar: Calendar,
  plus: Plus,
  search: Search,
  filter: Filter,
  more: MoreHorizontal,
  pause: Pause,
  play: Play,
  sheet: FileSpreadsheet,
  download: Download,
  spinner: Loader2,
  bot: Bot,
  user: User,
  alert: AlertCircle,
  checkCheck: CheckCheck,
  signal: Signal,
  brain: Brain,
};

export function Icon({
  name,
  className,
  size,
}: {
  name: string;
  className?: string;
  size?: number;
}) {
  const Cmp = map[name] ?? Info;
  return <Cmp className={className} size={size} />;
}
